#!/bin/bash

# Address book for upstream source trees 

get_linux(){
git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git $@ ;}

get_busybox(){
git clone git://busybox.net/busybox.git $@ ;}

get_syslinux(){
git clone git://git.kernel.org/pub/scm/boot/syslinux/syslinux.git $@ ;}

get_bash(){
git clone git://git.savannah.gnu.org/bash.git $@ ;}

get_coreutils(){
git clone git://git.sv.gnu.org/coreutils $@ ;}

get_squashfs(){
git clone git://git.kernel.org/pub/scm/fs/squashfs/squashfs-tools.git $@ ;}

get_buildroot(){
git clone git://git.buildroot.net/buildroot $@ ;}

get_htop(){
svn co https://svn.code.sf.net/p/htop/code/trunk $@ ;}

get_crosstool_devel(){
# not tested
hg clone http://crosstool-ng.org/hg/crosstool-ng "$@" ;}

get_crosstool_ng(){
# this is broken
wget http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.9.3.tar.bz2 -P $src
tar xjf src/cross* --transform  "s|crosstool-ng-1.9.3|"$@"|g" --absolute-names ;} 

get_nmap(){
svn co https://svn.nmap.org/nmap "$@" ;}

get_rsync(){
git clone git://git.samba.org/rsync.git "$@" ;}

get_aircrack_ng(){
svn co http://svn.aircrack-ng.org/trunk/ "$@" ;}

get_elfsprogs(){
git clone git://www.kernel.org/pub/scm/fs/ext2/e2fsprogs.git "$@" ;}

git_cpufrequtils(){
git clone git://www.kernel.org/pub/scm/utils/kernel/cpufreq/cpufrequtils.git "$@" ;}

get_util_linux(){
git clone git://www.kernel.org/pub/scm/utils/util-linux/util-linux.git  "$@" ;}

get_dash(){
git clone https://www.kernel.org/pub/scm/utils/dash/dash.git  "$@" ;}

get_pciutils(){
git clone git://www.kernel.org/pub/scm/utils/pciutils/pciutils.git  "$@" ;}

get_lm_sensors(){
svn co http://lm-sensors.org/svn/lm-sensors/trunk "$@" ;}

get_squashfs(){
git clone git://git.kernel.org/pub/scm/fs/squashfs/squashfs-tools.git "$@" ;}





