#!/bin/bash

make_util_linux()
{ 
if [[ -e "${work}"/util_linux ]]
then echo ok
else
	rsync -avP "${src}"/util_linux "${work}" 
	./autogen.sh
	./configure
	make -C $work/util_linux $cores ${CCTYPE}
fi
}
install_util_linux()
{ 
echo filler
}
