#!/bin/sh

# (C) 2014, pkg_stx, cgraf
# A simple package manager for static binaries.  
pkggrep()
{
        for i in $(while read -r j
                do      printf '%s\n' "$j"
                done < ${2})
        do
                case "$i" in
                        ${1}* )
                                printf '%s\n' "$i"
                                break
                                ;;
                        *)
                                ;;
                esac
        done
}

#pkggrep "$1" "$2"



WORKDR=$(pwd)/pkg_stx_work/ 
MIRROR="https://raw.githubusercontent.com/static-linux/static-binaries-i386/master/"

SOME="$(pwd)/config"
[ -f "$SOME" ] && . "$SOME"


MTADTA=$(pwd)/pkg_stx_work/METADATA
DTABSE=$(pwd)/pkg_stx_database/
#PKGNAM=$( grep -o  "^${2}-...*" $MTADTA | head -n 1) 
#PKGNAM=$( grep "${2}-...*" $MTADTA | head -n 1)
PKGNAM=$( pkggrep ${2} $MTADTA )






LOCALPAKS="0"

if [ -d "${MIRROR}" ]
then 	LOCALPAKS="1"
fi


mkdir -p "$WORKDR" "$DTABSE"


cd "$WORKDR"

case "$1" in 
 download) 	wget "${MIRROR}/${PKGNAM}.tar.gz"
		if [ "$LOCALPAKS" = "0" ]
                then    wget "${MIRROR}/${PKGNAM}.tar.gz"
                else    cp "${MIRROR}/${PKGNAM}.tar.gz" .
                fi
          	;; 
  install) 	
		if [ "$LOCALPAKS" = "0" ]
		then 	wget -O- "${MIRROR}/${PKGNAM}.tar.gz" | gunzip -c | tar xf - || exit 1 
		else	tar xf "${MIRROR}/${PKGNAM}.tar.gz" || exit 1
		fi
		mkdir -p "${DTABSE}/${PKGNAM}" 
		cd "$PKGNAM" 
		cp checksums "${DTABSE}/${PKGNAM}/checksums" 
		. "${WORKDR}/${PKGNAM}/checksums" 
		[ -f "$SOME" ] && . "$SOME"
		installd 
		cd "$WORKDR" 
		A=$( md5sum "${PKGNAM}/${2}" | awk '{ print $1}' ) 
		B=$( grep " ${2}" "$MTADTA" | awk 'NR==2{ print $2}') 
		echo "Verify checksums: ${A} ....  ${B}" 
		[ "$A" = "$B" ] && echo "Checksums match"
		[ "$A" = "$B" ] || echo "Checksum mismatch." 
		rm -rf "$PKGNAM" 
		;; 
   remove) 	if [ -e "${DTABSE}/${PKGNAM}/checksums" ]
		then 	. "${DTABSE}/${PKGNAM}/checksums" 
                	removed 
                	cd "$DTABSE"
                	rm -rf "$PKGNAM"
                	cd "$WORKDR"
           	else 	echo "Does not appear to have been installed by pkg_stx"
           	fi
           	;;
   search) 	grep "$2" "$MTADTA" 
           	;;
   update) 	if [ "$LOCALPAKS" = "0" ]
		then 	wget -O "$MTADTA" "${MIRROR}/METADATA"
		else	cp "${MIRROR}/METADATA" .
		fi 
           	;;
      src) 	if [ "$LOCALPAKS" = "0" ]
                then	wget -qO- "${MIRROR}/${PKGNAM}.src" | tar xvf - || exit 1 
		else    tar xf "${MIRROR}/${PKGNAM}.src" || exit 1
                fi
           	;;
        *) 	echo "Usage: pkg_stx [update|install|search|remove] <package name>" 
           	;; 
esac





